version: '2'
services:

  web:
    build:
      .
    ports:
      - 80:80
    volumes:
      - ./code:/code
      - ./config/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - ./logs/apache2:/var/log/apache2
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
      APACHE_PID_FILE: /var/run/apache2.pid
      APACHE_RUN_DIR: /var/run/apache2
      APACHE_LOCK_DIR: /var/lock/apache2
      APACHE_LOG_DIR: /var/log/apache2
    links:
        - "db:database"
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'test_pass' # TODO: Change this
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306